# Generated by Django 6.0.7 on 2026-07-14 10:11

import django.db.models.deletion
import nexora_ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexora_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ai_model',
            field=models.CharField(choices=[('nexora-1', 'Nexora 1 (Flash)'), ('nexora-pro', 'Nexora Pro'), ('nexora-ultra', 'Nexora Ultra')], default='nexora-1', max_length=50),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nexora_ai.models.document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('indexed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nexora_ai.conversation')),
            ],
        ),
    ]
